Articles section
GeorgeOblomov/nasa_app pull request #11
Opened 2022-02-22 06:20 UTC by GeorgeOblomov

2022-02-23 11:29 UTC, plastb1r requested changes

2022-02-23 11:29 UTC, plastb1r commented on lib/services/http_clients/dio_http_client.dart
> +    return jsonDecode(response.data ?? '');
а тут лучше оставил как было, даже оставил Map<String, Object?>
dynamic, как правило хорошего тона, используем по минимуму.

2022-02-23 11:29 UTC, plastb1r commented on lib/ui/articles_screen/articles_wm.dart
> +        // builder: (context) => Container(),
Это не нужно?

2022-02-24 06:27 UTC, GeorgeOblomov commented on lib/services/http_clients/dio_http_client.dart
> +    return jsonDecode(response.data ?? '');
Убрал dynamic, он по сути не нужен был. Но каст возвращать не стал, поскольку в разных сервисах получаем разные типы. Например в ArticlesService это уже не Map<String, Object>, а просто List.

2022-02-24 06:27 UTC, GeorgeOblomov commented on lib/ui/articles_screen/articles_wm.dart
> +        // builder: (context) => Container(),
Не нужно. Косяк.

2022-02-25 07:08 UTC, merged