Image screen
GeorgeOblomov/nasa_app pull request #7
Opened 2022-02-16 11:05 UTC by GeorgeOblomov

2022-02-17 09:16 UTC, plastb1r requested changes

2022-02-17 09:16 UTC, plastb1r commented on lib/ui/widgets/network_image_widget.dart
> +  void _onImageTap(BuildContext context, String url) {
лишний раз передавать context не обязательно - может путать. Он будет идентичный геттеру в State

2022-02-17 09:19 UTC, plastb1r commented
и еще будет полезно записывать видео экрана, если привнес весомые изменения в ui или запилил новую фичу.
Это ускоряет проверку ревью, тк не нужно будет каждому проверяющему запускать пр у себя и проверять, что действительно все ок

2022-02-17 13:29 UTC, GeorgeOblomov commented on lib/ui/widgets/network_image_widget.dart
> +  void _onImageTap(BuildContext context, String url) {
Может быть я не правильно понимаю, но это ведь StatelessWidget. Как мне иначе достучаться до контекста? GlobalKey заводить?

2022-02-18 07:55 UTC, plastb1r approved these changes

2022-02-18 08:06 UTC, merged