Save image
GeorgeOblomov/nasa_app pull request #8
Opened 2022-02-17 06:37 UTC by GeorgeOblomov

2022-02-17 09:35 UTC, plastb1r commented on lib/ui/nasa_image_screen/nasa_image_wm.dart
> +    model.saveImageToGallery(url).then((isSuccess) {
вот тут вопрос к тому, что будет, если мы отклоним разрешение на сохранение в начале. Можно немного упростить и не хранить или пытаться запросить доступ заного, а просто сразу перенаправлять в настройки мобилки

2022-02-17 09:37 UTC, plastb1r requested changes

2022-02-17 09:37 UTC, plastb1r commented on lib/ui/nasa_image_screen/nasa_image_wm.dart
> +      ).then((_) => model.isSavingProcess.value = false);
и если можно обойтись без then. , то лучше переписать это на async/await

2022-02-17 09:44 UTC, plastb1r commented on lib/ui/nasa_image_screen/nasa_image_wm.dart
> +      ).then((_) => model.isSavingProcess.value = false);
тупо читаемо и без колбеков

2022-02-17 13:45 UTC, GeorgeOblomov commented on lib/ui/nasa_image_screen/nasa_image_wm.dart
> +      ).then((_) => model.isSavingProcess.value = false);
Сделано.

2022-02-17 15:49 UTC, GeorgeOblomov commented on lib/ui/nasa_image_screen/nasa_image_wm.dart
> +    model.saveImageToGallery(url).then((isSuccess) {
Сделано.

2022-02-18 07:56 UTC, plastb1r approved these changes

2022-02-18 08:07 UTC, merged